In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=5)

df = pd.read_csv("sample.csv")

In [2]:
df.head(20)

Width  Length        Insect
0    2.30    8.56  Stick Insect
1    3.43    7.68  Stick Insect
2    1.32   12.32  Stick Insect
3    2.34    9.45  Stick Insect
4    1.87    7.45  Stick Insect
5    3.76   10.22  Stick Insect
6    1.65    9.43  Stick Insect
7    2.87    9.43  Stick Insect
8    3.00   10.56  Stick Insect
9    7.68    2.43      LadyBird
10   6.45    1.23      LadyBird
11   9.56    0.78      LadyBird
12   5.34    2.67      LadyBird
13   8.21    4.21      LadyBird
14   7.54    1.88      LadyBird
15   6.77    3.56      LadyBird
16   9.00    2.56      LadyBird
17   8.00    2.00      LadyBird
18   2.31   11.00  Stick Insect
19   7.00    4.50      LadyBird

In [3]:
heading = "Insect"
labelencoder = LabelEncoder()
df["Insect"] = labelencoder.fit_transform(df["Insect"])
insects = np.array(df["Insect"])

In [4]:
df.head(20)

Width  Length  Insect
0    2.30    8.56       1
1    3.43    7.68       1
2    1.32   12.32       1
3    2.34    9.45       1
4    1.87    7.45       1
5    3.76   10.22       1
6    1.65    9.43       1
7    2.87    9.43       1
8    3.00   10.56       1
9    7.68    2.43       0
10   6.45    1.23       0
11   9.56    0.78       0
12   5.34    2.67       0
13   8.21    4.21       0
14   7.54    1.88       0
15   6.77    3.56       0
16   9.00    2.56       0
17   8.00    2.00       0
18   2.31   11.00       1
19   7.00    4.50       0

In [5]:
kf = KFold(n_splits=10, shuffle=True)

In [6]:
error = []
for train, test in kf.split(df):
    predict_columns = df[["Width", "Length"]].iloc[train,:]
    x_train = np.array(predict_columns).reshape(-1, 1)
    target_column = df["Insect"].iloc[train]
    y_train = np.array(target_column).reshape(-1, 1)
    outcome = df["Insect"].iloc[test]
    y_test = np.array(outcome).reshape(-1, 1)
    print (x_train)

[[ 2.3 ]
 [ 8.56]
 [ 3.43]
 [ 7.68]
 [ 1.32]
 [12.32]
 [ 2.34]
 [ 9.45]
 [ 1.87]
 [ 7.45]
 [ 3.76]
 [10.22]
 [ 1.65]
 [ 9.43]
 [ 2.87]
 [ 9.43]
 [ 3.  ]
 [10.56]
 [ 7.68]
 [ 2.43]
 [ 6.45]
 [ 1.23]
 [ 9.56]
 [ 0.78]
 [ 8.21]
 [ 4.21]
 [ 6.77]
 [ 3.56]
 [ 9.  ]
 [ 2.56]
 [ 8.  ]
 [ 2.  ]
 [ 2.31]
 [11.  ]
 [ 7.  ]
 [ 4.5 ]]
[[ 3.43]
 [ 7.68]
 [ 1.32]
 [12.32]
 [ 2.34]
 [ 9.45]
 [ 1.87]
 [ 7.45]
 [ 3.76]
 [10.22]
 [ 1.65]
 [ 9.43]
 [ 2.87]
 [ 9.43]
 [ 3.  ]
 [10.56]
 [ 7.68]
 [ 2.43]
 [ 6.45]
 [ 1.23]
 [ 9.56]
 [ 0.78]
 [ 5.34]
 [ 2.67]
 [ 7.54]
 [ 1.88]
 [ 6.77]
 [ 3.56]
 [ 9.  ]
 [ 2.56]
 [ 8.  ]
 [ 2.  ]
 [ 2.31]
 [11.  ]
 [ 7.  ]
 [ 4.5 ]]
[[ 2.3 ]
 [ 8.56]
 [ 3.43]
 [ 7.68]
 [ 1.32]
 [12.32]
 [ 2.34]
 [ 9.45]
 [ 1.87]
 [ 7.45]
 [ 3.76]
 [10.22]
 [ 1.65]
 [ 9.43]
 [ 2.87]
 [ 9.43]
 [ 7.68]
 [ 2.43]
 [ 6.45]
 [ 1.23]
 [ 9.56]
 [ 0.78]
 [ 5.34]
 [ 2.67]
 [ 8.21]
 [ 4.21]
 [ 7.54]
 [ 1.88]
 [ 6.77]
 [ 3.56]
 [ 9.  ]
 [ 2.56]
 [ 8.  ]
 [ 2.  ]
 [ 7.  ]
 [ 4.5 ]]
[[ 2.3 ]
 [ 8.56]
 [ 1.32

In [7]:
def classification_model(model, data, predictors, outcome):
    """
    model.fit(data[predictors], data[outcome])
    predictions = model.predict(data[predictors])
    print(predictions)
    """
    kf = KFold(n_splits=10, shuffle=True)
    for train, test in kf.split(df):
        # Filter training data
        train_predictors = (data[predictors].iloc[train,:]).values
        print(train_predictors)
        # The target we're using to train the algorithm.
        train_target = data[outcome].iloc[train]

        # Training the algorithm using the predictors and target.
        model.fit(train_predictors, train_target)

In [8]:
outcome_var = "Insect"
model = knn
predictor_var = ["Width", "Length"]
classification_model(model, df, predictor_var, outcome_var)
model.predict([0.9, 0.8])

[[ 2.3   8.56]
 [ 3.43  7.68]
 [ 1.32 12.32]
 [ 2.34  9.45]
 [ 1.87  7.45]
 [ 3.76 10.22]
 [ 2.87  9.43]
 [ 3.   10.56]
 [ 6.45  1.23]
 [ 9.56  0.78]
 [ 5.34  2.67]
 [ 8.21  4.21]
 [ 7.54  1.88]
 [ 6.77  3.56]
 [ 9.    2.56]
 [ 8.    2.  ]
 [ 2.31 11.  ]
 [ 7.    4.5 ]]
[[ 3.43  7.68]
 [ 1.32 12.32]
 [ 2.34  9.45]
 [ 3.76 10.22]
 [ 1.65  9.43]
 [ 2.87  9.43]
 [ 3.   10.56]
 [ 7.68  2.43]
 [ 6.45  1.23]
 [ 9.56  0.78]
 [ 5.34  2.67]
 [ 8.21  4.21]
 [ 7.54  1.88]
 [ 6.77  3.56]
 [ 9.    2.56]
 [ 8.    2.  ]
 [ 2.31 11.  ]
 [ 7.    4.5 ]]
[[ 2.3   8.56]
 [ 3.43  7.68]
 [ 1.32 12.32]
 [ 2.34  9.45]
 [ 1.87  7.45]
 [ 3.76 10.22]
 [ 1.65  9.43]
 [ 2.87  9.43]
 [ 3.   10.56]
 [ 7.68  2.43]
 [ 6.45  1.23]
 [ 5.34  2.67]
 [ 8.21  4.21]
 [ 7.54  1.88]
 [ 6.77  3.56]
 [ 9.    2.56]
 [ 8.    2.  ]
 [ 2.31 11.  ]]
[[ 2.3   8.56]
 [ 3.43  7.68]
 [ 1.32 12.32]
 [ 2.34  9.45]
 [ 1.87  7.45]
 [ 3.76 10.22]
 [ 1.65  9.43]
 [ 2.87  9.43]
 [ 3.   10.56]
 [ 7.68  2.43]
 [ 6.45  1.23]
 [ 9.56  0.78]
 [ 5.34

ValueError: Expected 2D array, got 1D array instead:
array=[0.9 0.8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
kf = KFold(n_splits=10, shuffle=True)
for train, test in kf.split(df):
    # Filter training data
    train_predictors = (df[["Width", "Length"]].iloc[train,:]).values
    # The target we're using to train the algorithm.
    train_target = df["Insect"].iloc[train].values

    # Training the algorithm using the predictors and target.
    knn.fit(train_predictors, train_target)

In [9]:
knn.predict([[4, 6.5]])

array([0.8])

In [ ]:
df.head(20)